# Generated by Django 4.2.8 on 2026-09-07 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('Scooter', 'Scooter'), ('Adventure', 'Adventure'), ('Street', 'Street'), ('Cruiser', 'Cruiser'), ('Sports', 'Sports'), ('Bicycle', 'Bicycle')], max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('price_per_day', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField(default=2000)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('gear', models.CharField(max_length=60)),
                ('quantity', models.PositiveIntegerField(default=5, help_text='Units available in the fleet')),
                ('is_package_bike', models.BooleanField(default=False)),
                ('package_security_deposit', models.PositiveIntegerField(default=5999)),
            ],
        ),
        migrations.CreateModel(
            name='Homestay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=200)),
                ('price_per_night', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('image', models.URLField()),
                ('description', models.TextField()),
                ('guests', models.PositiveIntegerField(default=4)),
                ('beds', models.PositiveIntegerField(default=2)),
                ('amenities', models.CharField(help_text='Comma-separated list', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('homestay', 'Homestay'), ('bike', 'Bike')], max_length=10)),
                ('item_name', models.CharField(max_length=120)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('guests_or_days', models.PositiveIntegerField(help_text='Guests for a homestay, days for a bike')),
                ('rental_charge', models.PositiveIntegerField(default=0)),
                ('security_deposit', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.bike')),
                ('homestay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='core.homestay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
